fix minor syntax error
this avoids `  File "build\bdist.win-amd64\egg\mofa\core\simulate.py", line 141
    print "Not implemented"
                          ^
SyntaxError: Missing parentheses in call to 'print'`
warning during installation